//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC_Espaço_juvenil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSC_Espaço_juvenil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobilística.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap camiseta {
            get {
                object obj = ResourceManager.GetObject("camiseta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap carro {
            get {
                object obj = ResourceManager.GetObject("carro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap computador {
            get {
                object obj = ResourceManager.GetObject("computador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design gráfico.
        /// </summary>
        public static string design {
            get {
                return ResourceManager.GetString("design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se você sempre gostou de carros e admira alguém que faz manutenção em alguma oficina agora é a sua vez de ter novas experiências e desconbrir o incrível mundo dos automóveis..
        /// </summary>
        public static string DetailAuto {
            get {
                return ResourceManager.GetString("DetailAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profissionais que criam banners, identidade visual, folders, campanhas publicitárias esse profissional e criativo e inovador sempre sensível a tudo que ocorre ao seu redor. È um verdadeiro artista..
        /// </summary>
        public static string DetailDesigner {
            get {
                return ResourceManager.GetString("DetailDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temos cursos voltados para constura, mode e desgni com os melhores professores e profissionais do mercado fashion..
        /// </summary>
        public static string DetailModa {
            get {
                return ResourceManager.GetString("DetailModa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uma área que inova a cada dia necessitando de novos profissionais para grandes desafios. A área moveleira do SENAI é muito forte sendo referência internacional..
        /// </summary>
        public static string DetailMoveis {
            get {
                return ResourceManager.GetString("DetailMoveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uma área promissora de TI. Nela cria-se conexões entre computadores através de protocolos, técnicas e recursos físicos. É um mundo incrível só de ver dois computadores conversando né verdade? Imagine entender a fundo todo o processo de comunicação da grande rede mundial a Internet?.
        /// </summary>
        public static string DetailRedes {
            get {
                return ResourceManager.GetString("DetailRedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça manutenções em frers, geladeiras e ar condicionado com os melhores profissionais do mundo..
        /// </summary>
        public static string DetailRefrigeracao {
            get {
                return ResourceManager.GetString("DetailRefrigeracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nessa área você aprende a criar robôs. Já pensou criando seu própio robô?.
        /// </summary>
        public static string DetailRobotica {
            get {
                return ResourceManager.GetString("DetailRobotica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie softwares incíveis com as linguagens C# e Java aplicando conhecimentos de banco de dados e engenharia de sistemas..
        /// </summary>
        public static string DetailsSolu {
            get {
                return ResourceManager.GetString("DetailsSolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap illustrator {
            get {
                object obj = ResourceManager.GetObject("illustrator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logomarcasenai {
            get {
                object obj = ResourceManager.GetObject("logomarcasenai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap madeira {
            get {
                object obj = ResourceManager.GetObject("madeira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moda e Design.
        /// </summary>
        public static string moda {
            get {
                return ResourceManager.GetString("moda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móveis e Design.
        /// </summary>
        public static string moveis {
            get {
                return ResourceManager.GetString("moveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redes {
            get {
                object obj = ResourceManager.GetObject("redes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes de computadores.
        /// </summary>
        public static string redesd {
            get {
                return ResourceManager.GetString("redesd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrigeração.
        /// </summary>
        public static string refrigeração {
            get {
                return ResourceManager.GetString("refrigeração", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refrigerador {
            get {
                object obj = ResourceManager.GetObject("refrigerador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap robo {
            get {
                object obj = ResourceManager.GetObject("robo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robótica e Mecatrônica.
        /// </summary>
        public static string robotica {
            get {
                return ResourceManager.GetString("robotica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soluções de Software para negócios.
        /// </summary>
        public static string solu {
            get {
                return ResourceManager.GetString("solu", resourceCulture);
            }
        }
    }
}
